### ISSUE TITLE
TypeError: object blacksheep.messages.Response can't be used in 'await' expression

### ISSUE THREAD

**Issue by virajkanwade** [Cdayz/blacksheep-prometheus#46]
**Describe the bug**
When hitting /metrics path, it raises an error
```  File "blacksheep/baseapp.pyx", line 84, in blacksheep.baseapp.BaseApplication.handle
TypeError: object blacksheep.messages.Response can't be used in 'await' expression```

**To Reproduce**
Steps to reproduce the behavior:
Install blacksheep 1.2.6
Install blacksheep-prometheus
Follow code listed in blacksheep-prometheus readme.

**Expected behavior**
It should generate metrics response

**Comment by virajkanwade** [comment]
Is this lib being maintained?

**Comment by virajkanwade** [comment]
@Cdayz are you no longer maintaining this?

**Comment by Cdayz** [comment]
Give me an example of code, which produces this error;

I've tried with this code:
```python
from blacksheep.server import Application
from blacksheep_prometheus import PrometheusMiddleware, metrics

app = Application()

app.middlewares.append(PrometheusMiddleware())
app.router.add_get('/metrics/', metrics)

REDIRECT_COUNT = Counter("redirect_total", "Count of redirects", ("from_view",))

@app.router.get("/test")
async def some_view(request):
    REDIRECT_COUNT.labels(from_view="some_view").inc()
    return "redirect response here!"
```
And i use `uvicorn` to run this code like this: `uvicorn test:app`
And i'd not have any errors, when hitting `/metrics` endpoint, so provide more details about your problem, like:
- python version
- how you run code (e.g. uvicorn, or gunicorn command)
- minimal example of code which are produces error described in issue

**Comment by virajkanwade** [comment]
Hi @Cdayz I am following on the blacksheep example codes. https://github.com/Neoteroi/BlackSheepEmptyProject

If I change def metrics to async, it worked for me.

`async def metrics(request: Request) -> Response:`

**Comment by virajkanwade** [comment]
```
  • Installing prometheus-client (0.14.1)
  • Installing blacksheep-prometheus (0.1.6)
```

Python 3.10.3

`poetry run gunicorn -c lifecycle/gunicorn.conf.py app.asgi:app`

**Comment by Cdayz** [comment]
@virajkanwade , try to use blacksheep-prometheus==0.1.8, i've just released it, and make metrics view to be async
